### ISSUE TITLE
CodingBat - Warmup-1

### ISSUE THREAD

**Issue by lespabrandzulic82** [alptium/branko.spalovic#13]

**Comment by lespabrandzulic82** [comment]
@valentinacupac ,  I have finished Warmup1. 

![warmup1](https://user-images.githubusercontent.com/26182029/37298538-d96b4540-2620-11e8-9152-70ffaf1a107b.png)

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, correct.
