### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by lespabrandzulic82** [alptium/branko.spalovic#2]

**Comment by lespabrandzulic82** [comment]
I have done this task. @valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, please see my review comments https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World, section "Review", points 1 & 2, and make the correction.

**Comment by lespabrandzulic82** [comment]
i make correction on helloworld project@valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, I get an error when trying to execute the program.
Please send me the screenshot how it looks on your computer when executing this program.

![image](https://user-images.githubusercontent.com/677159/35886596-e4ca5cd6-0b91-11e8-941e-fe04aaa4a295.png)

**Comment by lespabrandzulic82** [comment]
looks the same...a will try to resolve problem@valentinacupac

**Comment by valentinajemuovic** [comment]
Thanks @lespabrandzulic82, I now added in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 21, that code should be executed and tested before committing. Thanks.

**Comment by lespabrandzulic82** [comment]
Sorry, my mistake, I have fixed hello-world@valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82 see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 14.

**Comment by lespabrandzulic82** [comment]
could you take a look if everything is ok now?@valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82:
1. See comment 14 here https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World

**Comment by lespabrandzulic82** [comment]
I have fixed this mistake @valentinacupac.

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, correct.
