### ISSUE TITLE
Gradebook

### ISSUE THREAD

**Issue by lespabrandzulic82** [alptium/branko.spalovic#4]

**Comment by lespabrandzulic82** [comment]
i have done this task@valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, did you write this code by yourself or is this from one of the other participants...

**Comment by lespabrandzulic82** [comment]
I needed a little help and I was looking to other's code. From now on I will do all codes by myself. @valentinacupac

**Comment by lespabrandzulic82** [comment]
should i try to do this in another way now@valentinacupac

**Comment by lespabrandzulic82** [comment]
i have done gradebook again @valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82:
See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comments 22, 23, 24.

Also, re-read the task https://github.com/alptium/valentina.cupac/wiki/05.-Gradebook regarding part about how total grade is computed.

**Comment by lespabrandzulic82** [comment]
i have replaced printing of average grade with total grade@valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82:
1. See 23 in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World
2. See 15 in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World
3. See 4 in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World
4. See 24 in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World

After you fix those, then I will check if anything further needs to be fixed.

**Comment by lespabrandzulic82** [comment]
I have fixed this mistakes @valentinacupac .

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, there are 15 lines which contain spelling mistakes, please re-check. Thanks.

**Comment by lespabrandzulic82** [comment]
I found spelling mistakes and fixed it. Could you take a look now? @valentinacupac

**Comment by valentinajemuovic** [comment]
Good @lespabrandzulic82.

One more small thing, I noticed that the grades are integers, but yet the sum is double. Is there a reason why the sum is a double, and not an integer?

**Comment by lespabrandzulic82** [comment]
I had a problem with calculating the average value when I entered the integer, so I put a double. is that mistake ? @valentinacupac

**Comment by lespabrandzulic82** [comment]
I have corrected, there is no average value in this task @valentinacupac

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, regarding your question - sum is integer, but average would be double.

Task is not correct, closing ticket.
