### ISSUE TITLE
Project Approval Request - Alptium Football

### ISSUE THREAD

**Issue by lespabrandzulic82** [alptium/branko.spalovic#6]
Hey @valentinacupac ,
@NikitaObradovic and I will work together on this project, the plan is like you proposed, he will do database part, I will do Java part, with mutual help...  We will make application like Nikita explained in his previous  comment.

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, this should have been in project "Java Project", so that I can see it, I will correct this now.

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, I have created the project and granted access to you and @NikitaObradovic
